from . import travel_security
from . import ir_attachment
from . import account_move
from . import account_move_line
from . import res_partner
from . import res_users
from . import sale_advance_payment_inv
from . import sale_order
from . import sale_order_line
from . import travel_airline
from . import travel_airport
from . import travel_departure
from . import travel_departure_accommodation
from . import travel_departure_flight
from . import travel_departure_price
from . import travel_demo
from . import travel_hotel
from . import travel_booking_participant
from . import travel_jamaah
from . import travel_package
