from . import test_booking
from . import test_booking_security
from . import test_departure
from . import test_itinerary
from . import test_jamaah
from . import test_master_data
from . import test_package
from . import test_phase2_hardening
from . import test_phase3_security
from . import test_phase3_accounting
from . import test_phase3_quota
from . import test_phase3_concurrency
from . import test_phase3_cancellation
from . import test_phase3_departure
from . import test_phase3_views
from . import test_phase4_reporting
from . import test_phase4_demo
from . import test_phase4_hardening
from . import test_phase4_acceptance
from . import test_security
from . import test_views
