from . import test_booking
from . import test_booking_security
from . import test_departure
from . import test_itinerary
from . import test_jamaah
from . import test_master_data
from . import test_package
from . import test_phase2_hardening
from . import test_phase3_security
from . import test_security
from . import test_views
